### ISSUE TITLE
Can't install github.com/josemyduarte/printer

### ISSUE THREAD

**Issue by Berezhnyk** [JosemyDuarte/DevsQuotesPrinter#3]
`go get github.com/josemyduarte/printer`
Is it not published?

**Comment by JosemyDuarte** [comment]
No, I didn't intend to be used as a library. It is more like an example project on how to do it. Take a look at https://github.com/JosemyDuarte/DevsQuotesPrinter/blob/master/textonimg.go and you will see how I did it.
